<?php

namespace AppBundle\Repository;

/**
 * ThemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThemRepository extends \Doctrine\ORM\EntityRepository
{
}
